---

- name: "Empty facts"
  set_fact:
    _sites: []
    _hosts: []

- name: "Get {{ item.group }} hosts"
  set_fact:
    _hosts: "{{ _hosts|d([]) + [ inv_host ] }}"
  with_inventory_hostnames:
    - "{{ item.group }}"
  loop_control:
    loop_var: inv_host
  when: item.status in (hostvars[inv_host]['status']).value

- name: "Sort _hosts"
  set_fact:
    _hosts: "{{ _hosts | sort }}"

- name: "Find sites"
  set_fact:
    _sites: "{{ _sites|d([]) + [ 'site_' + hostvars[_host]['site'] ] }}"
  loop: "{{ _hosts }}"
  loop_control:
    loop_var: _host
  when: hostvars[_host]['site'] != "orphans"

- name: "Make sites unique"
  set_fact:
    _sites: "{{ _sites | unique | sort }}"

- name: "Add Template Survey Loop"
  include_tasks: "add_template_survey_assign.yml"
  loop: "{{ item.name }}"
  loop_control:
    loop_var: _awx_template
  no_log: true

- name: "Add Template Survey | Enable Survey"
  include_tasks: "add_template_survey_update.yml"
  loop: "{{ item.name }}"
  loop_control:
    loop_var: _awx_template
  no_log: true
